# Generated by Django 5.2.1 on 2025-06-07 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dossiers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiermedical',
            name='medecin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_medecin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers_patient', to=settings.AUTH_USER_MODEL),
        ),
    ]
