# Generated by Django 5.2.1 on 2025-06-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('medecin', 'Médecin'), ('patient', 'Patient')], max_length=20),
        ),
    ]
